/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.Estructuras;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;

/**
 *
 * @author triamus
 * 664,523
 */
/*
Tamano pnlContenido: 630 * 550
*/
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());
    private static String user;
    private static String rol;
    /**
     * Creates new form FrmPrincipal
     */
    
    Estructuras almacen = new Estructuras();
    
    public FrmPrincipal(String user,String rol) {
        this.user = user;
        this.rol = rol;
        
        initComponents();
        aplicarHoverMenu(pnlMenu);
        
        
        if(!user.isEmpty()){
            //lblSeccionNombre.setText("Cargando...");
            //lblseccionRol.setText("Cargando...");
            lblSeccionNombre.setText(user);
            lblseccionRol.setText(rol);
        }
        

        // 1. Configurar la barra de scroll (Delgada, color azul y sin flechas)
        scrMenu.getVerticalScrollBar().setUI(new javax.swing.plaf.basic.BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new java.awt.Color(45, 90, 140); // Color de la barrita
                this.trackColor = new java.awt.Color(15, 32, 67);  // Fondo azul oscuro
            }

            @Override
            public java.awt.Dimension getPreferredSize(javax.swing.JComponent c) {
                return new java.awt.Dimension(8, super.getPreferredSize(c).height); // Ancho de 8px
            }

            @Override
            protected javax.swing.JButton createDecreaseButton(int orientation) {
                return crearBotonVacio();
            }

            @Override
            protected javax.swing.JButton createIncreaseButton(int orientation) {
                return crearBotonVacio();
            }

            private javax.swing.JButton crearBotonVacio() {
                javax.swing.JButton btn = new javax.swing.JButton();
                btn.setPreferredSize(new java.awt.Dimension(0, 0));
                return btn;
            }
        });

        // 2. Velocidad de la rueda del ratón
        scrMenu.getVerticalScrollBar().setUnitIncrement(16);

        // 3. Forzar políticas para que el scroll SÍ aparezca cuando sobrepase la altura
        scrMenu.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrMenu.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        // 4. Limpiar bordes y refrescar el contenedor
        scrMenu.setBorder(null);
        scrMenu.getViewport().setOpaque(false);
        scrMenu.revalidate();
        scrMenu.repaint();

        
    }
    
    private void aplicarHoverMenu(Container contenedor) {
    Color colorNormal = new Color(19,45,82);       // Azul base
    Color colorHover  = new Color(35, 75, 125);   // Azul claro al pasar el mouse

    for (Component comp : contenedor.getComponents()) {
        if (comp instanceof JButton) {
            JButton boton = (JButton) comp;
            
            boton.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent evt) {
                    boton.setBackground(colorHover);
                    boton.setCursor(new Cursor(Cursor.HAND_CURSOR));
                }

                @Override
                public void mouseExited(MouseEvent evt) {
                    boton.setBackground(colorNormal);
                    boton.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                }
            });
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();
        scrMenu = new javax.swing.JScrollPane();
        pnlMenu = new javax.swing.JPanel();
        btnFacturar = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        pnlSubInventario = new javax.swing.JPanel();
        btnArticulos = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        btnMesas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblMenuPrincipal = new javax.swing.JLabel();
        pnlSubCaja = new javax.swing.JPanel();
        btnEditarCaja = new javax.swing.JButton();
        btnMovCaja = new javax.swing.JButton();
        btnCajas = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pnlSeccion = new javax.swing.JPanel();
        lblSeccionNombre = new javax.swing.JLabel();
        lblseccionRol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitulo.setBackground(new java.awt.Color(22, 54, 94));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("El Rapidito");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(lblTitulo)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        getContentPane().add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 630, 50));

        pnlContenido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlContenido.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        getContentPane().add(pnlContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 630, 590));

        scrMenu.setBorder(null);
        scrMenu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlMenu.setBackground(new java.awt.Color(14, 38, 70));
        pnlMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenu.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenu.setMinimumSize(new java.awt.Dimension(32767, 32767));
        pnlMenu.setPreferredSize(new java.awt.Dimension(163, 600));
        pnlMenu.setVerifyInputWhenFocusTarget(false);

        btnFacturar.setBackground(new java.awt.Color(19, 45, 82));
        btnFacturar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFacturar.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/payment.png"))); // NOI18N
        btnFacturar.setText("Facturar");
        btnFacturar.addActionListener(this::btnFacturarActionPerformed);

        btnInventario.setBackground(new java.awt.Color(19, 45, 82));
        btnInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/production.png"))); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setMaximumSize(new java.awt.Dimension(32767, 32767));
        btnInventario.addActionListener(this::btnInventarioActionPerformed);

        pnlSubInventario.setBackground(new java.awt.Color(14, 38, 70));

        btnArticulos.setBackground(new java.awt.Color(20, 41, 82));
        btnArticulos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnArticulos.setForeground(new java.awt.Color(209, 224, 255));
        btnArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diet.png"))); // NOI18N
        btnArticulos.setText("Artículos");
        btnArticulos.addActionListener(this::btnArticulosActionPerformed);

        btnIngresos.setBackground(new java.awt.Color(20, 41, 82));
        btnIngresos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresos.setForeground(new java.awt.Color(209, 224, 255));
        btnIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salary.png"))); // NOI18N
        btnIngresos.setText("Ingresos");
        btnIngresos.addActionListener(this::btnIngresosActionPerformed);

        javax.swing.GroupLayout pnlSubInventarioLayout = new javax.swing.GroupLayout(pnlSubInventario);
        pnlSubInventario.setLayout(pnlSubInventarioLayout);
        pnlSubInventarioLayout.setHorizontalGroup(
            pnlSubInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubInventarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlSubInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSubInventarioLayout.setVerticalGroup(
            pnlSubInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMesas.setBackground(new java.awt.Color(19, 45, 82));
        btnMesas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMesas.setForeground(new java.awt.Color(255, 255, 255));
        btnMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chair.png"))); // NOI18N
        btnMesas.setText("Mesas");
        btnMesas.addActionListener(this::btnMesasActionPerformed);

        btnClientes.setBackground(new java.awt.Color(19, 45, 82));
        btnClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contact-new.png"))); // NOI18N
        btnClientes.setText("Clientes");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2ori (1).png"))); // NOI18N

        lblMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuPrincipal.setText("Menú Principal");

        pnlSubCaja.setBackground(new java.awt.Color(14, 38, 70));

        btnEditarCaja.setBackground(new java.awt.Color(20, 41, 82));
        btnEditarCaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditarCaja.setForeground(new java.awt.Color(209, 224, 255));
        btnEditarCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnEditarCaja.setText("Edición Cajas");
        btnEditarCaja.addActionListener(this::btnEditarCajaActionPerformed);

        btnMovCaja.setBackground(new java.awt.Color(20, 41, 82));
        btnMovCaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMovCaja.setForeground(new java.awt.Color(209, 224, 255));
        btnMovCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cashRegister.png"))); // NOI18N
        btnMovCaja.setText("Abrir / Cerrar");
        btnMovCaja.setToolTipText("");
        btnMovCaja.addActionListener(this::btnMovCajaActionPerformed);

        javax.swing.GroupLayout pnlSubCajaLayout = new javax.swing.GroupLayout(pnlSubCaja);
        pnlSubCaja.setLayout(pnlSubCajaLayout);
        pnlSubCajaLayout.setHorizontalGroup(
            pnlSubCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMovCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEditarCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSubCajaLayout.setVerticalGroup(
            pnlSubCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubCajaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditarCaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMovCaja)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnCajas.setBackground(new java.awt.Color(19, 45, 82));
        btnCajas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCajas.setForeground(new java.awt.Color(255, 255, 255));
        btnCajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cash.png"))); // NOI18N
        btnCajas.setText("Cajas");
        btnCajas.setMaximumSize(new java.awt.Dimension(32767, 32767));
        btnCajas.setMinimumSize(new java.awt.Dimension(32767, 32767));
        btnCajas.addActionListener(this::btnCajasActionPerformed);

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSubInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSubCaja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnMesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnFacturar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                .addGap(0, 32601, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlMenuLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnCajas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlMenuLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblLogo)
                                .addComponent(lblMenuPrincipal)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(lblMenuPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSubCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFacturar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSubInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes)
                .addContainerGap(32206, Short.MAX_VALUE))
        );

        scrMenu.setViewportView(pnlMenu);

        getContentPane().add(scrMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 540));

        pnlSeccion.setBackground(new java.awt.Color(14, 38, 70));
        pnlSeccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSeccionNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSeccionNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblSeccionNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/profile32x32.png"))); // NOI18N
        lblSeccionNombre.setText("Cargando...");
        lblSeccionNombre.setPreferredSize(new java.awt.Dimension(180, 30));

        lblseccionRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblseccionRol.setForeground(new java.awt.Color(255, 255, 255));
        lblseccionRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-profile (32x32).png"))); // NOI18N
        lblseccionRol.setText("Cargando...");
        lblseccionRol.setPreferredSize(new java.awt.Dimension(180, 30));

        javax.swing.GroupLayout pnlSeccionLayout = new javax.swing.GroupLayout(pnlSeccion);
        pnlSeccion.setLayout(pnlSeccionLayout);
        pnlSeccionLayout.setHorizontalGroup(
            pnlSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeccionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblseccionRol, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeccionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlSeccionLayout.setVerticalGroup(
            pnlSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeccionLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lblSeccionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblseccionRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //cuando se ejecuta el sistema
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pnlSubInventario.setVisible(false);
        pnlSubCaja.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnCajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajasActionPerformed
        // TODO add your handling code here:
        pnlSubCaja.setVisible(true);
    }//GEN-LAST:event_btnCajasActionPerformed

    private void btnMovCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovCajaActionPerformed
        // TODO add your handling code here:

        PnlOpsCajas OpsCajas = new PnlOpsCajas();
        OpsCajas.setSize(630,550);
        OpsCajas.setLocation(0,0);

        //elimine el contendio que hay
        pnlContenido.removeAll();
        //agregue lo que hay en el Pnl cajas a mi panel del contenido
        pnlContenido.add(OpsCajas);
        //Compruebe de que no se este saliendo nada fuera del system
        pnlContenido.revalidate();
        //Dibujelo
        pnlContenido.repaint();

        pnlSubCaja.setVisible(false);
    }//GEN-LAST:event_btnMovCajaActionPerformed

    private void btnEditarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCajaActionPerformed
        // TODO add your handling code here:
        PnlCajas cajas = new PnlCajas();
        cajas.setSize(630,550);
        cajas.setLocation(0,0);

        //elimine el contendio que hay
        pnlContenido.removeAll();
        //agregue lo que hay en el Pnl cajas a mi panel del contenido
        pnlContenido.add(cajas);
        //Compruebe de que no se este saliendo nada fuera del system
        pnlContenido.revalidate();
        //Dibujelo
        pnlContenido.repaint();
        pnlSubCaja.setVisible(false);
    }//GEN-LAST:event_btnEditarCajaActionPerformed

    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMesasActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        // TODO add your handling code here:
        pnlSubInventario.setVisible(false);
    }//GEN-LAST:event_btnIngresosActionPerformed

    //cuadno se presioan el boton
    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulosActionPerformed
        // TODO add your handling code here:
        pnlSubInventario.setVisible(false);
    }//GEN-LAST:event_btnArticulosActionPerformed

    //cuando se presiona el boton de inventario
    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        pnlSubInventario.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal("","").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticulos;
    private javax.swing.JButton btnCajas;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEditarCaja;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMesas;
    private javax.swing.JButton btnMovCaja;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblSeccionNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblseccionRol;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlSeccion;
    private javax.swing.JPanel pnlSubCaja;
    private javax.swing.JPanel pnlSubInventario;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JScrollPane scrMenu;
    // End of variables declaration//GEN-END:variables
}
