/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;

/**
 *
 * @author triamus
 * 664,523
 */
/*
Tamano pnlContenido: 630 * 550
*/
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());
    private static String user;
    private static String rol;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal(String user,String rol) {
        this.user = user;
        this.rol = rol;
        initComponents();
        aplicarHoverMenu(pnlMenu);
        
        
        if(!user.isEmpty()){
            //lblSeccionNombre.setText("Cargando...");
            //lblseccionRol.setText("Cargando...");
            lblSeccionNombre.setText(user);
            lblseccionRol.setText(rol);
        }
        
        
        
    }
    
    private void aplicarHoverMenu(Container contenedor) {
    Color colorNormal = new Color(19,45,82);       // Azul base
    Color colorHover  = new Color(35, 75, 125);   // Azul claro al pasar el mouse

    for (Component comp : contenedor.getComponents()) {
        if (comp instanceof JButton) {
            JButton boton = (JButton) comp;
            
            boton.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent evt) {
                    boton.setBackground(colorHover);
                    boton.setCursor(new Cursor(Cursor.HAND_CURSOR));
                }

                @Override
                public void mouseExited(MouseEvent evt) {
                    boton.setBackground(colorNormal);
                    boton.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                }
            });
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnFacturar = new javax.swing.JButton();
        btnCajas = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        pnlSubInventario = new javax.swing.JPanel();
        btnArticulos = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        btnMesas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblMenuPrincipal = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();
        pnlSeccion = new javax.swing.JPanel();
        lblSeccionNombre = new javax.swing.JLabel();
        lblseccionRol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(14, 38, 70));
        pnlMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenu.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenu.setMinimumSize(new java.awt.Dimension(32767, 32767));

        btnFacturar.setBackground(new java.awt.Color(19, 45, 82));
        btnFacturar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFacturar.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/payment.png"))); // NOI18N
        btnFacturar.setText("Facturar");
        btnFacturar.addActionListener(this::btnFacturarActionPerformed);

        btnCajas.setBackground(new java.awt.Color(19, 45, 82));
        btnCajas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCajas.setForeground(new java.awt.Color(255, 255, 255));
        btnCajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cash.png"))); // NOI18N
        btnCajas.setText("Cajas");
        btnCajas.setMaximumSize(new java.awt.Dimension(32767, 32767));
        btnCajas.setMinimumSize(new java.awt.Dimension(32767, 32767));
        btnCajas.addActionListener(this::btnCajasActionPerformed);

        btnInventario.setBackground(new java.awt.Color(19, 45, 82));
        btnInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/production.png"))); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setMaximumSize(new java.awt.Dimension(32767, 32767));
        btnInventario.addActionListener(this::btnInventarioActionPerformed);

        pnlSubInventario.setBackground(new java.awt.Color(14, 38, 70));

        btnArticulos.setBackground(new java.awt.Color(19, 45, 82));
        btnArticulos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnArticulos.setForeground(new java.awt.Color(255, 255, 255));
        btnArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diet.png"))); // NOI18N
        btnArticulos.setText("Artículos");
        btnArticulos.addActionListener(this::btnArticulosActionPerformed);

        btnIngresos.setBackground(new java.awt.Color(19, 45, 82));
        btnIngresos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresos.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salary.png"))); // NOI18N
        btnIngresos.setText("Ingresos");
        btnIngresos.addActionListener(this::btnIngresosActionPerformed);

        javax.swing.GroupLayout pnlSubInventarioLayout = new javax.swing.GroupLayout(pnlSubInventario);
        pnlSubInventario.setLayout(pnlSubInventarioLayout);
        pnlSubInventarioLayout.setHorizontalGroup(
            pnlSubInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubInventarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlSubInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSubInventarioLayout.setVerticalGroup(
            pnlSubInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresos)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnMesas.setBackground(new java.awt.Color(19, 45, 82));
        btnMesas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMesas.setForeground(new java.awt.Color(255, 255, 255));
        btnMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chair.png"))); // NOI18N
        btnMesas.setText("Mesas");
        btnMesas.addActionListener(this::btnMesasActionPerformed);

        btnClientes.setBackground(new java.awt.Color(19, 45, 82));
        btnClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contact-new.png"))); // NOI18N
        btnClientes.setText("Clientes");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2ori (1).png"))); // NOI18N

        lblMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuPrincipal.setText("Menú Principal");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCajas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSubInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFacturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 32604, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblLogo))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblMenuPrincipal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addGap(27, 27, 27)
                .addComponent(lblMenuPrincipal)
                .addGap(27, 27, 27)
                .addComponent(btnCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFacturar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSubInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes)
                .addContainerGap(32293, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 540));

        pnlTitulo.setBackground(new java.awt.Color(22, 54, 94));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("El Rapidito");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(lblTitulo)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        getContentPane().add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 630, 50));

        pnlContenido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlContenido.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        getContentPane().add(pnlContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 630, 590));

        pnlSeccion.setBackground(new java.awt.Color(14, 38, 70));
        pnlSeccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSeccionNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSeccionNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblSeccionNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/profile32x32.png"))); // NOI18N
        lblSeccionNombre.setText("Cargando...");

        lblseccionRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblseccionRol.setForeground(new java.awt.Color(255, 255, 255));
        lblseccionRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-profile (32x32).png"))); // NOI18N
        lblseccionRol.setText("Cargando...");

        javax.swing.GroupLayout pnlSeccionLayout = new javax.swing.GroupLayout(pnlSeccion);
        pnlSeccion.setLayout(pnlSeccionLayout);
        pnlSeccionLayout.setHorizontalGroup(
            pnlSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeccionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblseccionRol)
                    .addComponent(lblSeccionNombre))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlSeccionLayout.setVerticalGroup(
            pnlSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeccionLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lblSeccionNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblseccionRol)
                .addContainerGap())
        );

        getContentPane().add(pnlSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 170, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturarActionPerformed

    //cuando se ejecuta el sistema
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pnlSubInventario.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    //cuando se presiona el boton de inventario
    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        pnlSubInventario.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    //cuadno se presioan el boton
    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulosActionPerformed
        // TODO add your handling code here:
        pnlSubInventario.setVisible(false);
    }//GEN-LAST:event_btnArticulosActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        // TODO add your handling code here:
        pnlSubInventario.setVisible(false);
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnCajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajasActionPerformed
        // TODO add your handling code here:
        PnlCajas cajas = new PnlCajas();
        cajas.setSize(630,550);
        cajas.setLocation(0,0);
        
        //elimine el contendio que hay
        pnlContenido.removeAll();
        //agregue lo que hay en el Pnl cajas a mi panel del contenido
        pnlContenido.add(cajas);
        //Compruebe de que no se este saliendo nada fuera del system
        pnlContenido.revalidate();
        //Dibujelo
        pnlContenido.repaint();
    }//GEN-LAST:event_btnCajasActionPerformed

    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal("","").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticulos;
    private javax.swing.JButton btnCajas;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMesas;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblSeccionNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblseccionRol;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlSeccion;
    private javax.swing.JPanel pnlSubInventario;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables
}
