/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import java.util.ArrayList;
import Datos.ObjCaja;
import Datos.Estructuras;
import javax.swing.JOptionPane;
/**
 *
 * @author triamus
 */
public class PnlCajas extends javax.swing.JPanel {

    Estructuras almacen = new Estructuras();
    /**
     * Creates new form PnlCajas
     */
    public PnlCajas() {
        initComponents();
        
        
        // Botón Guardar
/*btnGuardar.setBackground(new java.awt.Color(40, 167, 69));
btnGuardar.setForeground(java.awt.Color.WHITE);
btnGuardar.setFocusPainted(false);
btnGuardar.setContentAreaFilled(false); // Quita el estilo nativo de Windows
btnGuardar.setOpaque(true);             // Fuerza el relleno del color de fondo
btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 120, 50), 1));
btnGuardar.setUI(new javax.swing.plaf.basic.BasicButtonUI()); // Desconecta la piel de Windows

// Botón Eliminar
btnBorrar.setBackground(new java.awt.Color(220, 53, 69));
btnBorrar.setForeground(java.awt.Color.WHITE);
btnBorrar.setFocusPainted(false);
btnBorrar.setContentAreaFilled(false);
btnBorrar.setOpaque(true);
btnBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 30, 45), 1));
btnBorrar.setUI(new javax.swing.plaf.basic.BasicButtonUI()); // Desconecta la piel de Windows*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLista = new javax.swing.JList<>();

        setMinimumSize(new java.awt.Dimension(630, 550));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Edición de Cajas");

        lblId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblId.setText("Identificación:");

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombre.setText("Nombre: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ubicación:");

        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtUbicacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dialog-ok-apply.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32x32gtk-delete.png"))); // NOI18N
        btnBorrar.setText("Eliminar");

        btnBuscar.setBackground(new java.awt.Color(19, 45, 82));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("...");

        lstLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addGap(304, 304, 304)
                        .addComponent(btnBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId)
                    .addComponent(btnBuscar))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBorrar))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(!validarCampos()){
            return;
        }
        
        int id = Integer.parseInt(txtId.getText());
        String nombre = txtNombre.getText();
        String ubicacion= txtUbicacion.getText();
        
        ObjCaja miCaja = new ObjCaja(id, nombre, ubicacion);
        almacen.agregarCaja(miCaja);
        
        almacen.mostrarCajas();
        
        txtId.setText("");
        txtNombre.setText("");
        txtUbicacion.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private boolean validarCampos(){
        
        if(txtId.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor complete este campo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            txtId.requestFocus();
            
            return false;
        }else if(txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor complete este campo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            txtNombre.requestFocus();
            return false;
        }else if(txtUbicacion.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor complete este campo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            txtUbicacion.requestFocus();
            return false;
        }
        
        try {
            // Intenta convertir el texto a número entero
            int numero = Integer.parseInt(txtId.getText());

            // Si llega aquí, significa que SÍ es un número válido
            
        } catch (NumberFormatException e) {
            // Si el usuario ingresó letras o símbolos, cae aquí
            JOptionPane.showMessageDialog(this, "Por favor ingrese solo números válidos", "Error de formato", JOptionPane.ERROR_MESSAGE);
            txtId.requestFocus(); // Devuelve el cursor al campo
            return false;
        }
        
        
            JOptionPane.showMessageDialog(this, "Datos guardados", "Exito", JOptionPane.INFORMATION_MESSAGE);
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstLista;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
